Validation
pawel-ozog/fast-search pull request #1
Opened 2022-04-05 12:58 UTC by kujawa98

2022-04-05 17:15 UTC, pawel-ozog requested changes

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/exception/ValidationException.java
> +public class ValidationException extends RuntimeException{
Please rename this class to better reflect its purpose, like: InvalidInputValidationException

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/service/ValidationService.java
> +        String illegalSymbols = "!@#$%^&*()_+-=";
Please refactor illegalSymbols and make it private static final.

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/service/ValidationService.java
> +                    throw new ValidationException("Illegal argument appeared");
Please add invalid word into the exception's message

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/Runner.java
> +                .peek(tuple -> validator.validate(tuple._2))
Please add additional 'onFailure' section and log out validation error

2022-04-05 17:15 UTC, pawel-ozog commented on src/test/java/com/example/search/engine/service/ValidationServiceTest.java
> +        List<String> words = Arrays.asList("firstWord", "secondWord", "thi@dW&rd");
How about an array having invalid word at index[0]?

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/helper/MilestoneResolver.java
> +        Assert.notNull(milestones, "milestones must not be null"); //throws exception if milestone is null
This comment is redundant. Please delete it.

2022-04-05 17:15 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/helper/MilestoneResolver.java
> +    public static MilestoneResolver of(SortedMap<Integer, Integer> milestones) { //of is a factory method
This comment is redundant. Please delete it.

2022-04-05 17:21 UTC, pawel-ozog requested changes

2022-04-05 17:21 UTC, pawel-ozog commented on src/main/java/com/example/search/engine/service/ValidationService.java
> +        input.stream()
We expect a very large number of inputs and here we do not care of the order. To increase performance please use parallelStream

2022-04-06 05:58 UTC, kujawa98 commented on src/main/java/com/example/search/engine/service/ValidationService.java
> +        String illegalSymbols = "!@#$%^&*()_+-=";
What do you mean by refactor?

2022-04-06 12:11 UTC, pawel-ozog commented on src/test/java/com/example/search/engine/service/ValidationServiceTest.java
> +    void testValidationException() {
Please use @ParametrizedTest to perform multiple assertions with one test

2022-04-07 11:20 UTC, pawel-ozog approved these changes

2022-04-07 11:21 UTC, merged